### ISSUE TITLE
Undefined docid on list of results

### ISSUE THREAD

**Issue by alevtina** [alliance-pcsg/primo-explore-report-problem#1]
I'm playing around with this package and I notice that the docid is "undefined" when the link is generated in the brief display (i.e., list of results):

http://ols.cuny.edu/onesearch/report_bug/?view_id=bb&record_id=undefined

However, it works as expected in the full display:

http://ols.cuny.edu/onesearch/report_bug/?view_id=bb&record_id=CUNY_BEPRESSsph_pubs-1089

**Comment by thatbudakguy** [comment]
Good catch - that's because I'm using `$location.search()` to grab the docID, which isn't present in the URL for brief results.

I guess there are two possible resolutions to this:
- if the brief result controller has access to `item`, use that to get the docID instead
- don't display the 'report problem' banner in the options menu for brief results at all.

The reason I bring up the latter is that our use case for developing this was mostly people wanting to report incorrect metadata or broken links, which usually don't present themselves until you get to the fulldisplay. Maybe there is a case where it's useful to do directly from the brief result, though?

**Comment by thatbudakguy** [comment]
Fixed by limiting it to fulldisplay, but leaving the issue open in case anyone comes up with a brief result use case.
